# Obtener todos los usuarios
GET http://localhost:3000/users

# Obtener un usuario por ID
GET http://localhost:3000/users/6783447a25b336004d7fbd27

# Crear un nuevo usuario
POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
    "firstName": "Jeimy",
    "lastName": "Alvarado",
    "email": "jeimy.alvarado13@gmail.com",
    "favoriteColor": "red",
    "birthDay": "2000/09/10"
}

# Actualizar un usuario existente
PUT http://localhost:3000/users/678346cc25b336004d7fbd28 HTTP/1.1
Content-Type: application/json

{
    "firstName": "Eduardo",
    "lastName": "Orellana",
    "email": "orellana@gmail.com",
    "favoriteColor": "orange",
    "birthDay": "2000/05/05"
}

DELETE http://localhost:3000/users/6783447a25b336004d7fbd27